import type { EcosystemEntry } from "./ecosystem";

/**
 * The approved `/ecosystem` list, kept apart from the types and helpers in `ecosystem.ts` so the
 * logic reads without scrolling past the data. Editorial: reviewed by a person, never fetched.
 */

/**
 * The day the list last changed, printed on the page as "Last updated on". Bump it in the
 * commit that adds, removes or rewrites an entry.
 */
export const ECOSYSTEM_UPDATED_ON = "2026-10-03";

export const ECOSYSTEM_ENTRIES: readonly EcosystemEntry[] = [
  {
    id: "zodl",
    name: "Zodl",
    category: "wallet",
    url: "https://zodl.com/",
    source: "Zcash mobile wallet",
  },
  {
    id: "zingo",
    name: "Zingo!",
    category: "wallet",
    url: "https://zingolabs.org/",
    source: "Zcash wallet by Zingo Labs",
  },
  {
    id: "unstoppable",
    name: "Unstoppable",
    category: "wallet",
    url: "https://unstoppable.money/",
    source: "multi-coin wallet with shielded Zcash",
  },
  {
    id: "edge",
    name: "Edge",
    category: "wallet",
    url: "https://edge.app/",
    source: "multi-coin wallet; private Zcash payments to names",
  },
  {
    id: "cake-wallet",
    name: "Cake Wallet",
    category: "wallet",
    url: "https://cakewallet.com/",
    source: "privacy-focused multi-coin wallet",
  },
  {
    id: "trust-wallet",
    name: "Trust Wallet",
    category: "wallet",
    url: "https://trustwallet.com/",
    source: "multi-coin wallet",
  },
  {
    id: "exodus",
    name: "Exodus",
    category: "wallet",
    url: "https://exodus.com/",
    source: "multi-coin wallet",
  },
  {
    id: "coinomi",
    name: "Coinomi",
    category: "wallet",
    url: "https://coinomi.com/",
    source: "multi-coin wallet",
  },
  {
    id: "brave-wallet",
    name: "Brave Wallet",
    category: "wallet",
    url: "https://brave.com/",
    source: "wallet built into the Brave browser",
  },
  {
    id: "ledger",
    name: "Ledger",
    category: "wallet",
    url: "https://ledger.com/",
    source: "hardware wallet",
  },
  {
    id: "trezor",
    name: "Trezor",
    category: "wallet",
    url: "https://trezor.io/",
    source: "hardware wallet",
  },
  {
    id: "keystone",
    name: "Keystone",
    category: "wallet",
    url: "https://shop.keyst.one/",
    source: "hardware wallet",
  },
  {
    id: "metamask-snap",
    name: "MetaMask Snap",
    category: "wallet",
    url: "https://snaps.metamask.io/",
    source: "Zcash add-on for MetaMask",
  },
  {
    id: "vizor",
    name: "Vizor",
    category: "wallet",
    url: "https://vizor.cash/",
    source: "Zcash wallet",
  },
  {
    id: "zkool",
    name: "Zkool",
    category: "wallet",
    url: "https://github.com/hhanh00/zkool2",
    source: "Zcash wallet, successor to YWallet",
  },
  {
    id: "gem-wallet",
    name: "Gem Wallet",
    category: "wallet",
    url: "https://gemwallet.com/",
    source: "open-source multi-coin wallet",
  },
  {
    id: "safepal",
    name: "SafePal",
    category: "wallet",
    url: "https://safepal.com/",
    source: "hardware and app wallet",
  },
  {
    id: "ssp-wallet",
    name: "SSP Wallet",
    category: "wallet",
    url: "https://sspwallet.io/",
    source: "multi-signature wallet",
  },
  {
    id: "vultisig",
    name: "Vultisig",
    category: "wallet",
    url: "https://vultisig.com/",
    source: "multi-party wallet",
  },
  {
    id: "zucchini",
    name: "Zucchini",
    category: "wallet",
    url: "https://zucchinifi.xyz/",
    source: "ZEC wallet",
  },
  {
    id: "zipher",
    name: "Zipher",
    category: "wallet",
    url: "https://github.com/atmospherelabs-dev/zipher-app",
    source: "open-source private Zcash wallet",
  },
  {
    id: "nozy-wallet",
    name: "Nozy Wallet",
    category: "wallet",
    url: "https://nozywallet.com/",
    source: "shielded Zcash wallet, private by default",
  },
  {
    id: "argos",
    name: "Argos",
    category: "wallet",
    url: "https://argos.sovright.com/",
    source: "desktop wallet for recovering legacy Zcash funds",
  },
  {
    id: "zapp",
    name: "Zapp",
    category: "wallet",
    url: "https://justzappit.xyz/",
    source: "shielded Zcash wallet with private messaging",
  },
  {
    id: "zafu",
    name: "Zafu",
    category: "wallet",
    url: "https://github.com/rotkonetworks/zafu",
    source: "coinholder grant application #29 · browser extension",
  },
  {
    id: "kraken",
    name: "Kraken",
    category: "exchange",
    url: "https://kraken.com/",
    source: "ZEC/USD market · Kraken's own API",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    category: "exchange",
    url: "https://coinbase.com/",
    source: "ZEC-USD market · Coinbase Exchange's own API",
  },
  {
    id: "binance",
    name: "Binance",
    category: "exchange",
    url: "https://binance.com/",
    source: "ZEC/USDT market · Binance's own API",
  },
  {
    id: "okx",
    name: "OKX",
    category: "exchange",
    url: "https://okx.com/",
    source: "ZEC-USDT market · OKX's own API",
  },
  {
    id: "kucoin",
    name: "KuCoin",
    category: "exchange",
    url: "https://kucoin.com/",
    source: "ZEC-USDT market · KuCoin's own API",
  },
  {
    id: "bitfinex",
    name: "Bitfinex",
    category: "exchange",
    url: "https://bitfinex.com/",
    source: "ZEC/USD market · Bitfinex's own API",
  },
  {
    id: "htx",
    name: "HTX",
    category: "exchange",
    url: "https://huobi.com/",
    source: "ZEC/USDT market · HTX's own API",
  },
  {
    id: "backpack",
    name: "Backpack",
    category: "exchange",
    url: "https://backpack.exchange/",
    source: "ZEC/USDC market · Backpack's own API",
  },
  {
    id: "robinhood",
    name: "Robinhood",
    category: "exchange",
    url: "https://robinhood.com/",
    source: "ZEC-USD market · Robinhood's own currency-pairs API",
  },
  {
    id: "bitcoinvn",
    name: "BitcoinVN",
    category: "exchange",
    url: "https://bitcoinvn.io/",
    source: "offers transparent and shielded ZEC · bitcoinvn.io · coinholder grant #1",
  },
  {
    id: "maya-protocol",
    name: "Maya Protocol",
    category: "exchange",
    url: "https://mayaprotocol.com/",
    source: "ZEC swaps · Maya's own Midgard API · this explorer's cross-chain index",
  },
  {
    id: "thorchain",
    name: "THORChain",
    category: "exchange",
    url: "https://thorchain.org/",
    source: "ZEC swaps · this explorer's cross-chain index",
  },
  {
    id: "leodex",
    name: "LeoDex",
    category: "exchange",
    url: "https://leodex.io/",
    source: "ZEC swaps via NEAR Intents · leodex.io",
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "exchange",
    url: "https://gemini.com/",
    source: "ZEC/USD market · Gemini's own API",
  },
  {
    id: "bitget",
    name: "Bitget",
    category: "exchange",
    url: "https://bitget.com/",
    source: "ZEC/USDT market · Bitget's own API",
  },
  {
    id: "gate",
    name: "Gate",
    category: "exchange",
    url: "https://gate.com/",
    source: "ZEC/USDT market · Gate's own API",
  },
  {
    id: "whitebit",
    name: "WhiteBIT",
    category: "exchange",
    url: "https://whitebit.com/",
    source: "ZEC/USDT market · WhiteBIT's own API",
  },
  {
    id: "poloniex",
    name: "Poloniex",
    category: "exchange",
    url: "https://poloniex.com/",
    source: "ZEC/USDT market · Poloniex's own API",
  },
  {
    id: "near-intents",
    name: "NEAR Intents",
    category: "exchange",
    url: "https://near-intents.org/",
    source: "ZEC swaps · this explorer's cross-chain index",
  },
  {
    id: "metro",
    name: "Metro (THORSwap)",
    category: "exchange",
    url: "https://metro.exchange/",
    source: "native ZEC swaps via NEAR Intents · coinholder grant application #32 · approved",
  },
  {
    id: "zcashtocash",
    name: "Zcash to Cash",
    category: "exchange",
    url: "https://zcashto.cash/",
    source: "sells ZEC for fiat through peer.xyz · coinholder grant application #60 · approved",
  },
  {
    id: "btcpay-server",
    name: "BTCPay Server",
    category: "payments",
    url: "https://github.com/btcpay-zcash/btcpayserver-zcash-plugin",
    source: "BTCPay Server plugin to accept ZEC",
  },
  {
    id: "cipherpay",
    name: "CipherPay",
    category: "payments",
    url: "https://cipherpay.app/",
    source: "non-custodial Zcash checkout for merchants",
  },
  {
    id: "flexa",
    name: "Flexa",
    category: "payments",
    url: "https://flexa.co/",
    source: "payments network",
  },
  {
    id: "nowpayments",
    name: "NOWPayments",
    category: "payments",
    url: "https://nowpayments.io/",
    source: "crypto payment gateway",
  },
  {
    id: "plisio",
    name: "Plisio",
    category: "payments",
    url: "https://plisio.net/",
    source: "crypto payment gateway",
  },
  {
    id: "binance-pay",
    name: "Binance Pay",
    category: "payments",
    url: "https://pay.binance.com/",
    source: "Binance's payment service",
  },
  {
    id: "zgo",
    name: "ZGo",
    category: "payments",
    url: "https://zgo.cash/",
    source: "Zcash payments app for merchants",
  },
  {
    id: "free2z",
    name: "Free2z",
    category: "payments",
    url: "https://free2z.cash/",
    source: "creator platform paid in ZEC",
  },
  {
    id: "tipz",
    name: "tipz",
    category: "payments",
    url: "https://tipz.cash/",
    source: "ZEC tips for creators",
  },
  {
    id: "livezec",
    name: "LiveZEC",
    category: "payments",
    url: "https://zec.live/",
    source: "private ZEC donations for streamers",
  },
  {
    id: "zec-market",
    name: "ZEC Market",
    category: "payments",
    url: "https://zecmarket.org/",
    source: "P2P marketplace settled in ZEC · zecmarket.org",
  },
  {
    id: "zecmap",
    name: "ZecMap",
    category: "payments",
    url: "https://zecmap.com/",
    source: "coinholder grant application #48 · places that accept ZEC",
  },
  {
    id: "zecbooks",
    name: "ZecBooks",
    category: "payments",
    url: "https://zecbooks.app/",
    source: "coinholder grant application #38 · view-only books",
  },
  {
    id: "zec-pay",
    name: "ZEC-Pay",
    category: "payments",
    url: "https://zec-pay.com/",
    source: "coinholder grant application #20 · pay ZEC invoices",
  },
  {
    id: "zecpay-rocks",
    name: "zecpay.rocks",
    category: "payments",
    url: "https://zecpay.rocks/",
    source: "self-destructing shielded Zcash invoices · zecpay.rocks",
  },
  {
    id: "crowdstore",
    name: "CrowdStore",
    category: "payments",
    url: "https://crowdstore.net/",
    source: "coinholder grant application #5 · P2P marketplace",
  },
  {
    id: "foundry",
    name: "Foundry",
    category: "mining",
    url: "https://foundrydigital.com/",
    source: "ZEC mining pool · named in recent blocks",
  },
  {
    id: "nicehash",
    name: "NiceHash",
    category: "mining",
    url: "https://nicehash.com/",
    source: "ZEC mining pool · named in recent blocks",
  },
  {
    id: "2miners",
    name: "2Miners",
    category: "mining",
    url: "https://zec.2miners.com/",
    source: "ZEC mining pool · named in recent blocks",
  },
  {
    id: "antpool",
    name: "Antpool",
    category: "mining",
    url: "https://v3.antpool.com/",
    source: "mining pool",
  },
  {
    id: "luxor",
    name: "Luxor",
    category: "mining",
    url: "https://luxor.tech/",
    source: "ZEC mining pool · named in recent blocks",
  },
  {
    id: "nanopool",
    name: "Nanopool",
    category: "mining",
    url: "https://zec.nanopool.org/",
    source: "ZEC mining pool",
  },
  {
    id: "viabtc",
    name: "ViaBTC",
    category: "mining",
    url: "https://viabtc.com/",
    source: "mining pool",
  },
  {
    id: "braiins-pool",
    name: "Braiins Pool",
    category: "mining",
    url: "https://braiins.com/",
    source: "mining pool",
  },
  {
    id: "f2pool",
    name: "F2Pool",
    category: "mining",
    url: "https://www.f2pool.com/",
    source: "ZEC pool (zec.f2pool.com) · f2pool.com",
  },
  {
    id: "sluicey",
    name: "Sluicey",
    category: "mining",
    url: "https://sluicey.xyz/",
    source: "non-custodial ZEC pool · named in 90 of 2,000 recent coinbases",
  },
  {
    id: "kupool",
    name: "KuPool",
    category: "mining",
    url: "https://www.kupool.com/",
    source: "named in 40 of 2,000 recent coinbases",
  },
  {
    id: "zecminingpool",
    name: "Zcash Mining Pool",
    category: "mining",
    url: "https://pool.zecminingpool.com/",
    source: "ZEC pool · named in 6 of 2,000 recent coinbases",
  },
  {
    id: "zebra",
    name: "Zebra",
    category: "infrastructure",
    url: "https://github.com/zcashfoundation/zebra",
    source: "the Zcash Foundation's full node",
  },
  {
    id: "zakura",
    name: "Zakura",
    category: "infrastructure",
    url: "https://zakura.com/",
    source: "the full node this explorer runs on",
  },
  {
    id: "zaino",
    name: "Zaino",
    category: "infrastructure",
    url: "https://github.com/zingolabs/zaino",
    source: "Zcash indexer by Zingo Labs",
  },
  {
    id: "lightwalletd",
    name: "lightwalletd",
    category: "infrastructure",
    url: "https://github.com/zcash/lightwalletd",
    source: "light-wallet backend server",
  },
  {
    id: "zinder",
    name: "Zinder",
    category: "infrastructure",
    url: "https://github.com/zcashfoundation/zinder",
    source: "GitHub topic: lightwalletd",
  },
  {
    id: "zec-rocks",
    name: "zec.rocks",
    category: "infrastructure",
    url: "https://hosh.zec.rocks/",
    source: "public light-wallet servers and their uptime monitor",
  },
  {
    id: "zcash-block-explorer",
    name: "Zcash Block Explorer",
    category: "explorer",
    url: "https://mainnet.zcashexplorer.app/",
    source: "block explorer",
  },
  {
    id: "cipherscan",
    name: "CipherScan",
    category: "explorer",
    url: "https://cipherscan.app/",
    source: "block explorer with privacy analytics",
  },
  {
    id: "zec-stats",
    name: "ZEC Stats",
    category: "explorer",
    url: "https://zecstats.com/",
    source: "network statistics dashboard",
  },
  {
    id: "shieldedscan",
    name: "ShieldedScan",
    category: "explorer",
    url: "https://shieldedscan.xyz/",
    source: "this explorer",
  },
  {
    id: "zcashinfo",
    name: "Zcash Info",
    category: "explorer",
    url: "https://zcashinfo.com/",
    source: "block explorer and network dashboard · zcashinfo.com",
  },
  {
    id: "lightwalletd-rs",
    name: "lightwalletd-rs",
    category: "infrastructure",
    url: "https://github.com/jpgonzalezra/lightwalletd-rs",
    source: "coinholder grant application #41",
  },
  {
    id: "zcash-names",
    name: "Zcash Names",
    category: "infrastructure",
    url: "https://zcashnames.com/",
    source: "personal names for shielded addresses · zcashnames.com",
  },
  {
    id: "zcash-me",
    name: "Zcash.me",
    category: "infrastructure",
    url: "https://zcash.me/",
    source: "coinholder grant application #23, #34 · verified Zcash identities",
  },
  {
    id: "cyphzec",
    name: "CyphZec",
    category: "explorer",
    url: "https://cyphzec.com/",
    source: "coinholder grant application #59",
  },
  {
    id: "librustzcash",
    name: "librustzcash",
    category: "developer",
    url: "https://github.com/zcash/librustzcash",
    source: "core Rust libraries for Zcash",
  },
  {
    id: "orchard",
    name: "orchard (Orchard & Ironwood)",
    category: "developer",
    url: "https://github.com/zcash/orchard",
    source: "implements the Orchard and Ironwood pools · orchard CHANGELOG",
  },
  {
    id: "ironwood",
    name: "Ironwood",
    category: "developer",
    url: "https://github.com/zcash/ironwood",
    source: "formal verification and documentation of the Ironwood pool",
  },
  {
    id: "sapling-crypto",
    name: "sapling-crypto",
    category: "developer",
    url: "https://github.com/zcash/sapling-crypto",
    source: "crates.io · depends on a Zcash crate",
  },
  {
    id: "halo2",
    name: "halo2",
    category: "developer",
    url: "https://github.com/zcash/halo2",
    source: "GitHub topic · zcash",
  },
  {
    id: "zips",
    name: "ZIPs",
    category: "developer",
    url: "https://github.com/zcash/zips",
    source: "Zcash Improvement Proposals",
  },
  {
    id: "android-sdk",
    name: "Android SDK",
    category: "developer",
    url: "https://github.com/zcash/zcash-android-wallet-sdk",
    source: "official Android wallet SDK",
  },
  {
    id: "swift-sdk",
    name: "Swift SDK",
    category: "developer",
    url: "https://github.com/zcash/zcash-swift-wallet-sdk",
    source: "official iOS wallet SDK",
  },
  {
    id: "zingolib",
    name: "zingolib",
    category: "developer",
    url: "https://github.com/zingolabs/zingolib",
    source: "Zingo Labs' wallet library",
  },
  {
    id: "ledger-zcash",
    name: "ledger-zcash",
    category: "developer",
    url: "https://github.com/zondax/ledger-zcash-rs",
    source: "crates.io · depends on a Zcash crate",
  },
  {
    id: "testnet-faucet",
    name: "Testnet faucet",
    category: "developer",
    url: "https://zcashfaucet.jinolabs.xyz/",
    source: "hands out testnet coins (TAZ)",
  },
  {
    id: "zecdev",
    name: "ZecDev",
    category: "developer",
    url: "https://github.com/zecdev",
    source: "developer tools for ZEC",
  },
  {
    id: "zeckit",
    name: "ZecKit",
    category: "developer",
    url: "https://docs.zeckit.xyz/",
    source: "coinholder grant application #44",
  },
  {
    id: "zap1",
    name: "ZAP1",
    category: "developer",
    url: "https://github.com/Frontier-Compute/zap1",
    source: "coinholder grant application #31 · memo attestation protocol",
  },
  {
    id: "zec-ironwood-reconcile",
    name: "zec-ironwood-reconcile",
    category: "developer",
    url: "https://github.com/steven3002/zec-ironwood-reconcile",
    source: "coinholder grant application #46",
  },
  {
    id: "zcash-hw-wallet-sdk",
    name: "Zcash HW Wallet SDK",
    category: "developer",
    url: "https://github.com/wh00hw/zcash-hw-wallet-sdk",
    source: "coinholder grant application #28",
  },
  {
    id: "electric-coin-company",
    name: "Electric Coin Company",
    category: "organisation",
    url: "https://electriccoin.co/",
    source: "created Zcash",
  },
  {
    id: "zcash-foundation",
    name: "Zcash Foundation",
    category: "organisation",
    url: "https://zfnd.org/",
    source: "builds Zebra and supports the protocol",
  },
  {
    id: "zcash-community-grants",
    name: "Zcash Community Grants",
    category: "organisation",
    url: "https://zcashcommunitygrants.org/",
    source: "the community grants programme",
  },
  {
    id: "financial-privacy-foundation",
    name: "Financial Privacy Foundation",
    category: "organisation",
    url: "https://financialprivacyfoundation.org/",
    source: "runs the coinholder grants programme",
  },
  {
    id: "shielded-labs",
    name: "Shielded Labs",
    category: "organisation",
    url: "https://shieldedlabs.net/",
    source: "donation-funded Zcash support organisation",
  },
  {
    id: "zechub",
    name: "ZecHub",
    category: "organisation",
    url: "https://zechub.org/",
    source: "community wiki and education",
  },
  {
    id: "valar-group",
    name: "Valar Group",
    category: "organisation",
    url: "https://github.com/valargroup",
    source: "private on-chain voting for Zcash holders",
  },
  {
    id: "qedit",
    name: "QEDIT",
    category: "organisation",
    url: "https://qed-it.com/",
    source: "Zcash cryptography and audits",
  },
  {
    id: "zcash-labs",
    name: "Zcash Labs",
    category: "organisation",
    url: "https://zcashlabs.org/",
    source: "coinholder grant application #60",
  },
  {
    id: "project-tachyon",
    name: "Project Tachyon",
    category: "organisation",
    url: "https://tachyon.z.cash/",
    source: "coinholder grant application #50",
  },
  {
    id: "zcash-community",
    name: "Zcash Community",
    category: "community",
    url: "https://zcashcommunity.com/",
    source: "community site and guides",
  },
  {
    id: "zecweekly",
    name: "ZecWeekly",
    category: "community",
    url: "https://zechub.substack.com/",
    source: "weekly Zcash newsletter",
  },
  {
    id: "zcash-brasil",
    name: "Zcash Brasil",
    category: "community",
    url: "https://zcashbr.com/",
    source: "Brazilian Zcash community",
  },
  {
    id: "pgpz",
    name: "PGPZ",
    category: "community",
    url: "https://community.pgpz.org/",
    source: "Zcash community forum",
  },
  {
    id: "zshieldher",
    name: "ZShieldHer",
    category: "community",
    url: "https://zshieldher.com/",
    source: "financial-privacy education for safety",
  },
  {
    id: "openzcash",
    name: "OpenZcash",
    category: "explorer",
    url: "https://openzcash.org/",
    source: "Zcash grants and governance data",
  },
  {
    id: "zec-bounties",
    name: "ZEC Bounties",
    category: "community",
    url: "https://bounties.zechub.wiki/",
    source: "ZecHub's bounty platform",
  },
  {
    id: "cypherschool",
    name: "CypherSchool",
    category: "community",
    url: "https://cypherschool.online/",
    source: "cypherpunk privacy and Zcash learning",
  },
  {
    id: "zcash-grants-hub",
    name: "Zcash Grants Hub",
    category: "community",
    url: "https://zgrantshub.com/",
    source: "coinholder grant application #24",
  },
  {
    id: "gleyo",
    name: "Gleyo",
    category: "community",
    url: "https://gleyo.app/",
    source: "coinholder grant application #43",
  },
];
