#!/usr/bin/env python3
"""
Derive the Zebra mark the /network page shows from the Zcash Foundation's own badge.

    python3 brand/derive-zebra-badge.py

Reads  brand/zebra-badge-official.png   (128x128 RGBA — github.com/ZcashFoundation/zebra,
                                         book/theme/favicon.png, fetched 2026-09-07)
Writes src/components/zebra-badge.generated.ts

**This is the site's first RASTER mark, and the reason is recorded rather than left implicit.**
Every other mark here is path data: the Foundation publishes the badge only as a raster (the
Zebra book carries a PNG favicon and no vector), and the badge is a gear holding a striped
zebra head in three colours — a shape whose tracing would be hours of work for a mark drawn at
18px, where the tracer's error budget is the whole glyph. A faithful quantised copy of the
publisher's own pixels is more accurate than any trace, and "an inaccurate logo is worse than
an honest initial" cuts against redrawing it. The CSP already admits `data:` images.

Quantised to 32 colours, no dither, so the file is small (about 2.4 KB, 3.2 KB as base64 —
under the 4 KB the plan allowed) and byte-stable across runs: the same input yields the same
module, so a change is a diff someone can read. Re-run when the Foundation changes its badge.
"""

import base64
import hashlib
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "brand" / "zebra-badge-official.png"
OUT = ROOT / "src" / "components" / "zebra-badge.generated.ts"
COLOURS = 32
MAX_BYTES = 4096


def main():
    raw = SRC.read_bytes()
    im = Image.open(io.BytesIO(raw)).convert("RGBA")
    if im.size != (128, 128):
        raise SystemExit(f"expected a 128x128 badge, got {im.size}")
    q = im.quantize(colors=COLOURS, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE)
    buf = io.BytesIO()
    q.save(buf, "PNG", optimize=True)
    png = buf.getvalue()
    if len(png) > MAX_BYTES:
        raise SystemExit(f"quantised badge is {len(png)} bytes, over the {MAX_BYTES} budget")
    b64 = base64.b64encode(png).decode("ascii")
    lines = [
        "// GENERATED by brand/derive-zebra-badge.py — do not edit. Re-run the script instead.",
        "// The Zcash Foundation's Zebra badge (github.com/ZcashFoundation/zebra, book/theme/favicon.png),",
        f"// quantised to {COLOURS} colours. Source sha256 {hashlib.sha256(raw).hexdigest()[:16]}…",
        "",
        f"export const ZEBRA_BADGE_PX = {im.size[0]};",
        f"export const ZEBRA_BADGE_BYTES = {len(png)};",
        f'export const ZEBRA_BADGE_DATA_URI = "data:image/png;base64,{b64}";',
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}: {len(png)} bytes as PNG, {len(b64)} as base64")


if __name__ == "__main__":
    main()
