#!/usr/bin/env python3
"""Derive the MCP server's advertised icon from the site icon.

The MCP spec (2025-11-25) lets a server name an icon in `serverInfo.icons`. A `data:` URI is
used rather than a URL because clients SHOULD reject icons from an origin other than the
server's, and the site icon lives on shieldedscan.xyz while the server is api.shieldedscan.xyz.
96 px keeps the initialize response small while staying sharp at the sizes clients draw.

    python3 brand/derive-mcp-icon.py   # writes server/mcp-icon.generated.ts
"""
import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "public" / "icon-512.png"
OUT = ROOT / "server" / "mcp-icon.generated.ts"
SIZE = 96

img = Image.open(SRC).convert("RGB").resize((SIZE, SIZE), Image.LANCZOS)
buf = io.BytesIO()
img.save(buf, format="PNG", optimize=True)
b64 = base64.b64encode(buf.getvalue()).decode("ascii")

OUT.write_text(
    "// GENERATED by brand/derive-mcp-icon.py from public/icon-512.png — do not edit by hand.\n"
    f"/** The site icon at {SIZE}x{SIZE}, PNG, base64 — the MCP server's advertised icon. */\n"
    f'export const MCP_ICON_PNG_BASE64 =\n  "{b64}";\n'
    f"export const MCP_ICON_SIZE = {SIZE};\n"
)
print(f"wrote {OUT.relative_to(ROOT)}: {len(buf.getvalue())} bytes png, {len(b64)} chars base64")
