#!/usr/bin/env python3
"""
Derive the share-card font subsets from the site's own webfonts.

    python3 brand/subset-og-fonts.py

Reads  public/fonts/JetBrainsMono-{Regular,ExtraBold}.woff2   (what the site serves)
Writes src/features/og/fonts.generated.ts                     (what satori can read)

Two reasons this exists rather than a pair of committed TTFs somebody once exported:

  * **satori cannot parse woff2.** The transaction share card is rendered by `next/og`
    (satori) inside a Netlify function, and it needs the raw glyf outlines — so the site's
    served format is unusable there. Everything else on the site reads `public/fonts/`
    through `next/font/local`, and this keeps the card's type derived from those exact
    files rather than from a lookalike.
  * **The subset is what makes it affordable.** A full JetBrains Mono face converts to
    ~270 KB, and the card's own text is uppercase Latin, digits, hex and a handful of
    marks — so the subsets come to ~7 KB each, which is what belongs inside a function
    bundle that cold-starts on a scraper's request.

The output is a TypeScript module holding the two faces as base64 rather than two .ttf
files, and that is not a stylistic choice. The card renders inside the Next server runtime,
where the documented `fetch(new URL("./font.ttf", import.meta.url))` pattern fails outright
— `file:` fetches are "not implemented... yet..." there, which surfaces as an HTTP 500 from
the image route and nothing else. Reading the file with `fs` instead would depend on the
deployment tracing a path it cannot see statically. A module import cannot fail either way,
and `brand/generate.mjs` already embeds these same faces as base64 for the same reason.

`CHARS` is the closed set the card may print. A glyph the card wants and this set omits
renders as a blank box, which is precisely the failure JetBrains Mono's missing U+25D0 ◐
already cost this project once — so the redaction bar on the card is DRAWN (divs), never
the ▓ character, and no box-drawing or block glyph is listed here. `og-fonts.test.ts`
holds this set against every string the card can produce.
"""

import base64
import pathlib
from fontTools import subset

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src/features/og/fonts.generated.ts"

# Uppercase Latin and digits carry the card; lowercase is the wordmark and the host; the
# marks are the ones the card's own strings use — the arrow of a flow path, the middot
# separators, the ≈ that qualifies a converted figure.
CHARS = "".join(
    sorted(
        set(
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            "abcdefghijklmnopqrstuvwxyz"
            "0123456789"
            " ./,:—…·→≈$%()[]-+_"
        )
    )
)

FACES = [("Regular", "REGULAR", 400), ("ExtraBold", "EXTRABOLD", 800)]

parts = [
    "// GENERATED by brand/subset-og-fonts.py — do not edit. Re-run the script instead.",
    "//",
    "// The share card's type: JetBrains Mono, subset to the characters the card can print,",
    "// as TTF (satori cannot read woff2) embedded base64 (the runtime can neither fetch a",
    "// file: URL nor be relied on to trace one). ~7 KB a face before encoding.",
    "",
]

for weight, const, css_weight in FACES:
    src = ROOT / "public/fonts" / f"JetBrainsMono-{weight}.woff2"
    # Subset to a temporary file and read it back: fontTools can write to stdout, but
    # capturing that means swapping sys.stdout, which is more moving parts than a file.
    tmp = ROOT / f"src/features/og/.{const.lower()}.tmp.ttf"
    subset.main(
        [
            str(src),
            f"--text={CHARS}",
            f"--output-file={tmp}",
            "--flavor=",
            "--layout-features=",
            "--no-hinting",
            "--desubroutinize",
        ]
    )
    data = tmp.read_bytes()
    tmp.unlink()
    parts.append(f"/** JetBrains Mono {weight}, weight {css_weight}. */")
    parts.append(f'export const JBM_{const}_B64 =')
    parts.append(f'  "{base64.b64encode(data).decode()}";')
    parts.append("")
    print(f"JBM_{const}_B64  {len(data) // 1024} KB raw")

OUT.write_text("\n".join(parts))
print(f"wrote {OUT.relative_to(ROOT)}  {OUT.stat().st_size // 1024} KB")
