import type { ApiGroup } from "../types";

export const PRIVACY_GROUP: ApiGroup = {
  id: "privacy",
  label: "Transaction privacy",
  endpoints: [
    {
      id: "tx-privacy",
      method: "GET",
      path: "/v1/transactions/{txid}/privacy",
      title: "The privacy reading of one transaction",
      description:
        "Which shielded pools a transaction touched, which way value crossed the transparent boundary, the net shielded flow (only where a pool publishes a value balance), and whether it was a pool migration. `notKnowable` lists what the chain does not record: sender, recipient, and the payment/change split.",
      params: [
        {
          name: "txid",
          kind: "path",
          type: "string (64 hex)",
          required: true,
          description: "The transaction id. Case-insensitive; anything else is a 400.",
          example: "25d87ba678308c4b88b5b3cfebf4eda388d2e3523f2cf93c03ea2894b0fe8a1e",
        },
      ],
      exampleResponse: `{
  "txid": "25d87ba678308c4b88b5b3cfebf4eda388d2e3523f2cf93c03ea2894b0fe8a1e",
  "blockHeight": 3428150,
  "kind": "shielded",
  "direction": "shielded",
  "pools": [
    "ironwood",
    "orchard"
  ],
  "netShieldedZat": -30000,
  "netShieldedBasis": "sapling + orchard + ironwood value balances; sprout publishes no per-bundle balance",
  "publicValueZat": null,
  "migration": {
    "fromPools": [
      "orchard"
    ],
    "toPool": "ironwood",
    "amountZat": 300000000
  },
  "bundles": {
    "sprout": null,
    "sapling": null,
    "orchard": {
      "actions": 4,
      "valueBalanceZat": -300030000
    },
    "ironwood": {
      "actions": 2,
      "valueBalanceZat": 300000000
    }
  },
  "notKnowable": [
    "sender",
    "recipient",
    "payment-vs-change-split",
    "shielded-amounts"
  ],
  "asOf": 1753795200,
  "unknowns": {
    "publicValueZat": "shielded"
  }
}`,
      notes: [
        "The example — and the playground's prefilled txid — is a real mainnet turnstile migration: 3 ZEC crossing Orchard → Ironwood at block 3,428,150, generated by running the actual response mapper over the captured block. What the live API returns for it differs only in `asOf`.",
        "A fully shielded transaction has `publicValueZat: null` with reason `shielded` — that null is a Zcash feature, not a data gap. `migration` is non-null only when the movement is provable: no transparent side, exactly one pool gaining.",
      ],
      toolNotes: [
        "A fully shielded transaction's `publicValueZat` is null with reason `shielded`: encrypted by design, not missing. `migration` is set only when provable: no transparent side and exactly one pool gaining.",
      ],
    },
  ],
};
